services:
  - type: web
    name: your-service-name
    env: node
    region: oregon
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: MONGO_URI
        value: mongodb+srv://ravinder22:UpNBRpxioiGWxSZs@ravindernyalakati08.ovdjwp3.mongodb.net/syoft?retryWrites=true&w=majority&appName=ravindernyalakati08
      - key: JWT_SECRET
        value: myverylongandsecurejwtsecretkey
